frouriojs/frourio

README.md
SSIA.
preview: https://github.com/yokinist/frourio/tree/fix-broken-link#support
=> docs: fix broken twitter image link

CHANGELOG.md, __test__/index.spec.ts, package.json, servers/all/$server.ts, servers/minimum/$server.ts, servers/noMulter/$server.ts, servers/noTypedParams/$server.ts, servers/noValidator/$server.ts, src/buildServerFile.ts
=> chore(release): 0.18.2

.github/workflows/nodejs.yml, CHANGELOG.md, package.json, servers/all/$server.ts, servers/noMulter/$server.ts, servers/noTypedParams/$server.ts, servers/noValidator/$server.ts, src/buildServerFile.ts, src/createControllersText.ts
=> chore(release): 0.21.1

CHANGELOG.md, package.json, yarn.lock
=> chore(release): 0.21.3

CHANGELOG.md, __test__/index.spec.ts, package.json, servers/all/$server.ts, servers/all/api/controller.ts, servers/all/api/index.ts, servers/all/validators/index.ts, src/buildServerFile.ts, src/createControllersText.ts, yarn.lock
=> chore(release): 0.23.0

CHANGELOG.md, __test__/build.spec.ts, __test__/index.spec.ts, package.json, servers/all/$server.ts, servers/all/validators/index.ts, servers/noTypedParams/$server.ts, servers/noValidator/$server.ts, src/buildServerFile.ts, yarn.lock
=> chore(release): 0.24.0

__test__/unit.spec.ts, src/createControllersText.ts, src/createDefaultFilesIfNotExists.ts
Context: It is discussed feature to prevent auto-generation when `git checkout` is run.
=> feat: not create files if there are already any files

src/buildServerFile.ts, src/checkRequisites.ts
=> chore: show warning messages for validator users

.github/pull_request_template.md, .github/workflows/release-drafter-main.yml
- resolves #
- resolves #
- ...
Please upvode with reacting as :+1: to express your agreement.
=> ci: fix typo and update

.github/dependabot.yml, .github/pull_request_template.md, .github/workflows/nodejs.yml, .github/workflows/release-drafter.yml
- resolves #
- resolves #
- ...
=> ci: fix typo and update node ver for building

README.md
- resolves #
- resolves #
- ...
=> docs: update readme branch names

CHANGELOG.md, src/createControllersText.ts
- resolves #
- resolves https://github.com/frouriojs/frourio/issues/226
- ...
=> feat: show the error when multiple path param folders made

.github/workflows/nodejs.yml, jest.config.ts, package.json, servers/all/api/$api.ts, servers/minimum/api/$api.ts, servers/noMulter/api/$api.ts, servers/noTypedParams/api/$api.ts, servers/noValidator/api/$api.ts, yarn.lock
- resolves #
- resolves #
- ...
=> chore: update modules

.github/workflows/nodejs.yml, CHANGELOG.md, package.json
- resolves #
- resolves #
- ...
=> release v0.29.1

CHANGELOG.md
- resolves #
- resolves #
- ...
=> chore: release v0.30.0

CHANGELOG.md, servers/all/$server.ts, servers/minimum/$server.ts, servers/noMulter/$server.ts, servers/noTypedParams/$server.ts, servers/noValidator/$server.ts, src/buildServerFile.ts, src/createControllersText.ts
- resolves #
- resolves #
- ...
=> fix: type definitions of $server.ts

CHANGELOG.md, __test__/index.spec.ts, servers/all/$server.ts, servers/minimum/$server.ts, servers/noMulter/$server.ts, servers/noValidator/$server.ts, src/buildServerFile.ts
- resolves #
- resolves #
- ...
=> fix: use safeParse for validation error

.github/workflows/nodejs.yml, servers/all/$server.ts, src/buildServerFile.ts, tests/index.spec.ts
- resolves #
- resolves #
- ...
=> release v1.2.1

package-lock.json, package.json, servers/all/$server.ts, servers/all/validators.ts, src/createControllersText.ts, src/getArrayElementType.ts, tests/index.spec.ts
- resolves #
- resolves #
- ...
=> release v1.3.0

servers/all/$server.ts, servers/all/validators.ts, src/buildServerFile.ts, src/createControllersText.ts, tests/build.spec.ts, tests/index.spec.ts
- resolves #
- resolves #
- ...
=> release v1.3.1
